travis:
  secure:
    BINSTAR_TOKEN: nH0NSV4K6fB4/FaRMv3/cbsTJ1v6gVQZbUADFPVOMQw6Ap/7DNTmsJXmjpg+yblIRX6E83BGaix6pgiHhWr7e8bI4XoKMikBuimr3gLhqJjcpqYpl1cCrNu0WlWgWz3V04FokaSH7urgpZ6odCdkqeYRgUmPd/YAMoF1GYgbz+NV2OFfiJAZ7s/+aNxnZqzTKpcJNSnlhi+2tKYFLD+kzFjtcCbgA+H3XbBxuuT+jb9GqtwzgafASphcH1nfiyOsfEy9L94ku5agMCVyQApf2GJ/O3AMaAa5oURr1zGnJuU0cSZeA+wcvWP+YmbmKlGGj47fiHaJol0OWrHIGzpGKlG+6MT/YfJjgjjFi5ke5s94P84gJH6Z+cdykBDYvNdXds6WjAm5Qp8nZiAN4rL2pglTDe9LXDVk7qARrxsNj6twTZhtsN9tY5IyIHy57m7LSIllD56CuaXxubujqm4B/sqN5vNJSDdHeqbeHAaLBzJJIu3yMr7DPg3B9OIsP8G4CQ91ecqlO4+ikVFTBykEnmuxxK48u2d7dPgPvPL0LseOlZ/CcZgfm+75DfcFvBtmGyFIavPHcZ63cWdvx37ofBJH4el9rVFcCTsi9mX97MV0UXetvPAF2Ip/t2gRhxhcqJL8yR9LYHcjBiqAlakVEQ9A1Aa609H1mMY6ouXua2U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
